version: "3"

services:

  market-server:
    image: ramesesinc/local-market-server:v001
    container_name: market-server
    restart: always

    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"

    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf

    ports:
      - "8074:8070"

    volumes:
      - ../../_res/connections:/apps/server/services/apps/enterprise/connections
      - ../../_custom/datasources/marketds:/apps/server/services/datasources/mainds
      - ./modules/rameses-gov-etracs-market-services.jar:/apps/server/services/apps/enterprise/modules/rameses-gov-etracs-market-services.jar
