version: "3"

services:

  mail-obo: 
    image: ramesesinc/mail-server:latest
    container_name: mail-obo
    restart: always
    logging: 
      driver: "json-file"
      options:
        max-file: "5"
        max-size: "10m"
    env_file:
      - ./env.conf
      - ../../_res/env.conf
      - ../../_custom/env.conf
    ports:
      - "2526:25"
