version: "3"

services:
  
  download-server:
    image: nginx:latest
    container_name: download-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    environment:
      TZ: "Asia/Manila"
    ports:
      - "8000:80"
    volumes:
      - ../download/conf.d:/etc/nginx/conf.d
      - ../download/resources:/resources


  etracs25-server:
    image: ramesesinc/etracs25-server-city:255.02.003
    container_name: etracs25-server
    restart: always
    logging:
      driver: "json-file"
      options: 
        max-file: "5"
        max-size: 10m
    env_file:
      - ./env.conf
      - ../_custom/env.conf
    ports:
      - "8060:8060"
      - "8061:8061"
      - "8070:8070"
      - "8080:8080"
    volumes:
      - ../_res/connections:/apps/etracs25/connections/ext
      - ./modules:/apps/etracs25/modules
      - ./dev_modules/rameses-gov-etracs-rptis-city-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-city-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-coordinator-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-coordinator-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-landtax-online-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-landtax-online-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-landtax-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-landtax-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-landtax-report-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-landtax-report-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-online-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-online-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-report-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-report-services.jar
      - ./dev_modules/rameses-gov-etracs-rptis-sms-services.jar:/services/modules/etracs/rameses-gov-etracs-rptis-sms-services.jar
